name: 'BUILD'

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true

jobs:
  source_build:
    name: 'Source'
    runs-on: [ubuntu-22.04]
    permissions:
      contents: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          repository: 'tbocek/obs-source-all'
          fetch-depth: 0

      - name: 'Create source artifact'
        run: |
          CURRENT=$(pwd)
          mkdir /tmp/build && cd /tmp/build
          git clone https://github.com/obsproject/obs-studio.git
          git -C obs-studio checkout tags/${{ github.event.inputs.tag }}
          git -C obs-studio submodule update --init --recursive 
          prefix=obs-studio-${{ github.event.inputs.tag }}
          ARTIFACT_NAME=${prefix}.tar.gz
          echo "artifact: $ARTIFACT_NAME"
          # create a tarball with *all* the sources
          # - prefix paths with 'obs-studio/' (since we are creating the tarball from within the source dir)
          # - exclude all repository files
          # - make the tarball reproducible
          tar -cvzf $CURRENT/${ARTIFACT_NAME}  --transform='s|^\.|obs-studio|'  --exclude-vcs --exclude-vcs-ignores --exclude '.git*'  --sort=name  --owner=0 --group=0 --numeric-owner --pax-option="exthdr.name=%d/PaxHeaders/%f,delete=atime,delete=ctime" --mtime="${commit_date}"  .
          # announce artifact for upload
          cd $CURRENT
          echo "FILE_NAME=${ARTIFACT_NAME}" >> $GITHUB_ENV
          git tag ${{ github.event.inputs.tag }}
          git push origin --tags

      - name: 'Release'
        uses: ncipollo/release-action@v1
        with:
          name: '${{ github.event.inputs.tag }}'
          owner: 'tbocek'
          repo: 'tbocek/obs-source-all'
          tag: '${{ github.event.inputs.tag }}'
          artifacts: '${{ env.FILE_NAME }}'

      - name: 'Upload source artifact'
        uses: actions/upload-artifact@v3
        with:
          name: 'obs-studio-source-${{ github.event.inputs.tag }}'
          path: '${{ github.workspace }}/${{ env.FILE_NAME }}'